# Generated by Django 4.0 on 2023-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0002_subtitle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
