# Generated by Django 4.0 on 2023-11-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0003_alter_subtitle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
