# Generated by Django 4.0 on 2023-11-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0004_alter_subtitle_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='target_audience',
            field=models.CharField(choices=[('obcan', 'Občan'), ('podnikatel', 'Podnikatel'), ('student', 'Študent'), ('dochodca', 'Dôchodca')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='text',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
