# Generated by Django 4.0 on 2023-11-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0005_alter_article_target_audience_alter_subtitle_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='text',
            field=models.TextField(),
        ),
    ]
