# Generated by Django 4.0 on 2023-11-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0009_alter_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Target Audience',
                'verbose_name_plural': 'Target Audiences',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='target_audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticlePage.targetaudience'),
        ),
    ]
