# Generated by Django 4.0 on 2023-11-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0012_articletype_department_article_article_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
    ]
