# Generated by Django 4.0 on 2023-12-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0014_lifesituation_article_life_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticlePage.department'),
        ),
        migrations.AlterField(
            model_name='lifesituation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
