# Generated by Django 4.0 on 2024-01-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlePage', '0015_alter_article_department_alter_lifesituation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='icon_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
