# Generated by Django 4.0 on 2023-12-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
