# Generated by Django 4.0 on 2023-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='signed_by',
        ),
        migrations.AddField(
            model_name='document',
            name='signed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
