# Generated by Django 4.0 on 2023-12-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentPage', '0002_remove_attachment_signed_by_document_signed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='signed_by',
            field=models.CharField(max_length=100),
        ),
    ]
